appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: sMNYY5YXSPU3mfYCyrr551q52vx1ePrmJanBfW663Xk/CXGjo9Zlv3Cvi1n4Do0VJC/sppCJPuiYYnSHSgaJjYXJ/Zcm2XrGrcY7EVnfNOqdeadfeQT97824yh8ph46wrirz8DJZ8I1Kpj8TC0lYOWA3hFhWR2h7Kl3TTiwkV34aODo+Z+KkAnQ08jyOyeWgy4zYhlZoe4ZAn6PArWH9XFGdy7LRMzqWWza4KfqplzB45WDxCjVI7MB9TxEkgowj+0I3XYwaAPQs/cPrQILMXPtUrby5nrqPtcFtSkoqcGlG3UDTM8CtPagJbAsZsyj4AQxvVLr5oj3qXhbrbxju0Q6J+vuF8I+JAqJeb0attG4sTY/1diGBpv380l8JrC1onuyb22Lf4yfNRyPIJ+yhtgXu8AYfpE026f1jxNqzHX2/EWw1yhRnFyl1ZMmBWvD4YWz9a2aRzCHFNYuhmmdMiOg1ZNUrd8Gx8X5gg7tAkeJBvCwdnVeeXN8UmCGp8zQDoNqOKmJVla0IXyXN35oZlEMXbqWoTxFT2gAcEgqxg2BOhiZMbDSpR+aceY7VCUYazJITmnP5HGJjhu3z16oq3C7yBHNv//RmFpWL8ie7ZVfaFSA1k62FU9oatg3LeiTN3ONE/954A3aU3ClcRB9/HYFZCmqIwpDByNCZElp+a7c=}
