travis:
  secure:
    BINSTAR_TOKEN: LZa9V9xhVf9IHqa3ylqyJ13zM3+bd5KMLKC36PQmcJoDmhlxzK0VEBLbf+1RvKkUeprEnnrKzwSk1nZV9y3qQwu/jkLfucYdq3E9krg0xvI2473uPyjhVH8+DOrQ7+T2qm2q42DZI3hFeZyENlchLUAjcQI0499pR5xCkkEbTF/ANJqquWdQCzyP6NTJaHt74GUxuDoO3cVWULAgj7YoZ2TQdgpmwD59EprqM9aH6ELQpBWXUIl4hAPBTeDm0ZZcqLOxfdYopJ81IxyoYA7Tc7p9VxzZ4qJH3j5WC9IZj5fFFYJj+g4/HADp5siTGwConydWX9y+xXMuhwwSZPYHmijWKEDkT6tkKLsOleMOU5gF793HaarHENTi/DrOfxRFHdYkLYQvp6tylq8qouxAaHh6TytzgWLm6e7cKxz/yMHSK+caQMc2ze1qWcXuNaJxED4rF/0MGH5xHodgeYS53LpcgRdvjhk+LYAeOweds0MsBu1OP9FPQU2VNXz2Uz3/SgMQlS6JYnI9ZDrNEBx4o/b+065r5oVQseEqcQ71tmOhSopXebJcu7OpCOle0/OsANl4hj3pLok+Cd7m9SZxGGdKO1tYCMvVi0M3bM5TtgcgYZjiqQywWnWUf32RP2V7LvBy1CGJS6T7BBaouRl5y8uBmV0eKQxoX5/cFb/FeiY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
